name: Enviar Recordatorios Diarios de Check-in (Público)

on:
  schedule:
    # Programa la ejecución a las 10:00 AM UTC (que es 08:00 AM en Argentina, GMT-3).
    # Ajusta esta hora según tus necesidades.
    - cron: '0 10 * * *'

  workflow_dispatch: # Permite disparar el workflow manualmente desde GitHub

jobs:
  trigger_checkin_reminders:
    runs-on: ubuntu-latest # El entorno en el que se ejecutará la acción

    steps:
      - name: Mostrar hora de inicio
        run: echo "Iniciando la solicitud HTTP para recordatorios a las $(date -u) UTC..."

      - name: Realizar solicitud HTTP a la app de Render
        run: |
          # Usamos curl para hacer la petición HTTP GET.
          # Simplemente accede a la URL sin cabeceras de autenticación.
          curl -X GET "https://proyectoppvi.onrender.com/enviarLinkCheckin"

          echo "Solicitud HTTP enviada. Verifica los logs de Render para los detalles de ejecución de la tarea."

      - name: Mostrar hora de finalización
        run: echo "Solicitud finalizada a las $(date -u) UTC."
